name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install-pcap
      run: sudo apt install libpcap-dev -y > /dev/null
    - name: make
      run: make
